<!-- Определение типа документа -->
<!DOCTYPE STUDENTS [
  <!ELEMENT STUDENTS (STUDENT+)>
  <!ELEMENT STUDENT (NAME, SURNAME, AGE, UNIVERSITY, COURSE, GROUP, FACULTY, SPECIALITY)>
  <!ELEMENT NAME (#PCDATA)>
  <!ELEMENT SURNAME (#PCDATA)>
  <!ELEMENT AGE (#PCDATA)>
  <!ELEMENT UNIVERSITY (#PCDATA)>
  <!ELEMENT COURSE (#PCDATA)>
  <!ELEMENT GROUP (#PCDATA)>
  <!ELEMENT FACULTY (#PCDATA)>
  <!ELEMENT SPECIALITY (#PCDATA)>
]>
<STUDENTS>
  <STUDENT>
    <NAME>VERONIKA</NAME>
    <SURNAME>KARELINA</SURNAME>
    <AGE>18</AGE>
    <UNIVERSITY>BSTU</UNIVERSITY>
    <COURSE>1</COURSE>
    <GROUP>4</GROUP>
    <FACULTY>INFORMATION TECHNOLOGY</FACULTY>
    <SPECIALITY>INFORMATION SYSTEMS AND TECHNOLOGIES</SPECIALITY>
  </STUDENT>
  <STUDENT>
    <NAME>ARTYOM</NAME>
    <SURNAME>ZHIDIK</SURNAME>
    <AGE>17</AGE>
    <UNIVERSITY>BSTU</UNIVERSITY>
    <COURSE>1</COURSE>
    <GROUP>4</GROUP>
    <FACULTY>INFORMATION TECHNOLOGY</FACULTY>
    <SPECIALITY>INFORMATION SYSTEMS AND TECHNOLOGIES</SPECIALITY>
  </STUDENT>
  <STUDENT>
    <NAME>DARYA</NAME>
    <SURNAME>SHUNKEVICH</SURNAME>
    <AGE>18</AGE>
    <UNIVERSITY>BSTU</UNIVERSITY>
    <COURSE>1</COURSE>
    <GROUP>2</GROUP>
    <FACULTY>INFORMATION TECHNOLOGY</FACULTY>
    <SPECIALITY>INFORMATION SYSTEMS AND TECHNOLOGIES</SPECIALITY>
  </STUDENT>
</STUDENTS>