=== zhdkrt/BSTU_1_SEM/КЯР/scheme.xsd
<!-- XSD - описание структуры XML-документа -->
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CATALOG">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="BOOK">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NAME" type="xs:string" />
              <xs:element name="AUTHOR" type="xs:string" />
              <xs:element name="GENRE" type="xs:string" />
              <xs:element name="PRICE" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zhdkrt/BSTU_1_SEM/КЯР/LR-21.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="LR-21.css"?>
<CATALOG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scheme.xsd">
    <BOOK>
        <NAME>Метро 2033</NAME>
        <AUTHOR>Дмитрий Глуховский</AUTHOR>
        <GENRE>Роман</GENRE>
        <PRICE>30 BYN</PRICE>
    </BOOK>
    <BOOK>
        <NAME>1984</NAME>
        <AUTHOR>Джордж Оруэлл</AUTHOR>
        <GENRE>Антиутопия</GENRE>
        <PRICE>25 BYN</PRICE>
    </BOOK>
    <BOOK>
        <NAME>Война и Мир</NAME>
        <AUTHOR>Лев Толстой</AUTHOR>
        <GENRE>Роман</GENRE>
        <PRICE>40 BYN</PRICE>
    </BOOK>
</CATALOG>
